"""Add account type to users model

Revision ID: 20f79cec6059
Revises: 7d1f55a90942
Create Date: 2023-09-11 08:36:22.082603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f79cec6059'
down_revision = '7d1f55a90942'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.String(), nullable=False, server_default='Free'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
