"""password reset token

Revision ID: 2421a05c2052
Revises: 39a7ad134d1d
Create Date: 2024-07-01 12:38:51.644167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2421a05c2052'
down_revision = '39a7ad134d1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_token')
    # ### end Alembic commands ###
