"""Add EndpointLog table

Revision ID: 398dd86ab1f8
Revises: 20cd1f24d894
Create Date: 2023-05-10 20:04:09.606382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398dd86ab1f8'
down_revision = '20cd1f24d894'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('time_taken', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_logs_endpoint'), 'endpoint_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_endpoint_logs_id'), 'endpoint_logs', ['id'], unique=False)
    op.create_index(op.f('ix_endpoint_logs_username'), 'endpoint_logs', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoint_logs_username'), table_name='endpoint_logs')
    op.drop_index(op.f('ix_endpoint_logs_id'), table_name='endpoint_logs')
    op.drop_index(op.f('ix_endpoint_logs_endpoint'), table_name='endpoint_logs')
    op.drop_table('endpoint_logs')
    # ### end Alembic commands ###
