"""message

Revision ID: 39a7ad134d1d
Revises: 5f8ac33b897b
Create Date: 2024-07-01 12:37:44.743347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a7ad134d1d'
down_revision = '5f8ac33b897b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_logs', sa.Column('password_reset_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint_logs', 'password_reset_token')
    # ### end Alembic commands ###
