"""add profile fields to users and endpoint_logs

Revision ID: 439468131b44
Revises: d8e3b4a9f2c1
Create Date: 2026-04-04 10:58:02.348160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439468131b44'
down_revision = 'd8e3b4a9f2c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_logs', sa.Column('organization_type', sa.String(), nullable=True))
    op.add_column('endpoint_logs', sa.Column('sector', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sector', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sector')
    op.drop_column('users', 'organization_type')
    op.drop_column('users', 'full_name')
    op.drop_column('endpoint_logs', 'sector')
    op.drop_column('endpoint_logs', 'organization_type')
    # ### end Alembic commands ###
