"""add user_usage table

Revision ID: 5c35ed08c5d4
Revises: 439468131b44
Create Date: 2026-05-29 01:46:50.756269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c35ed08c5d4'
down_revision = '439468131b44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'day', name='pk_user_usage')
    )
    op.create_index(op.f('ix_user_usage_day'), 'user_usage', ['day'], unique=False)
    op.create_index(op.f('ix_user_usage_user_id'), 'user_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_usage_user_id'), table_name='user_usage')
    op.drop_index(op.f('ix_user_usage_day'), table_name='user_usage')
    op.drop_table('user_usage')
    # ### end Alembic commands ###
