"""adding new database model audio_transcriptions

Revision ID: 5f8ac33b897b
Revises: 20f79cec6059
Create Date: 2024-06-19 15:55:27.428582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8ac33b897b'
down_revision = '20f79cec6059'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('audio_file_url', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded', sa.DateTime(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_transcriptions_id'), 'audio_transcriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_transcriptions_id'), table_name='audio_transcriptions')
    op.drop_table('audio_transcriptions')
    # ### end Alembic commands ###
