"""Add date field to monitoring EndpointLog model

Revision ID: 7d1f55a90942
Revises: 37f37c47862b
Create Date: 2023-05-22 09:24:23.756997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1f55a90942'
down_revision = '37f37c47862b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_logs', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint_logs', 'date')
    # ### end Alembic commands ###
