"""Updating user model by adding authentication type

Revision ID: 8d04a8912370
Revises: b5bc33ce99aa
Create Date: 2024-12-09 19:08:49.668576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d04a8912370'
down_revision = 'b5bc33ce99aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_type', sa.String(), nullable=False, server_default='Credentials'))

    # Remove the server default after adding the column
    op.alter_column('users', 'oauth_type', server_default=None)
    # ### end Alembic commands ###
    op.execute("UPDATE users SET oauth_type = 'Credentials'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_type')
    # ### end Alembic commands ###
