"""add language field audio transcription

Revision ID: 8ecfceb8e277
Revises: 2421a05c2052
Create Date: 2024-11-07 14:21:48.237326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ecfceb8e277'
down_revision = '2421a05c2052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_transcriptions', sa.Column('language', sa.String(length=255), nullable=True))
    op.alter_column('endpoint_logs', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint_logs', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('audio_transcriptions', 'language')
    # ### end Alembic commands ###
