"""making oauth_type nullable

Revision ID: 95cf3c1435d0
Revises: 8d04a8912370
Create Date: 2024-12-13 11:49:56.960265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cf3c1435d0'
down_revision = '8d04a8912370'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'oauth_type',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
    op.execute("UPDATE users SET oauth_type = Credentials")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'oauth_type',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
