"""Add organization field to user and monitoring models

Revision ID: 96762ef5fd5e
Revises: 398dd86ab1f8
Create Date: 2023-05-22 08:30:22.576687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96762ef5fd5e'
down_revision = '398dd86ab1f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_logs', sa.Column('organization', sa.String(), nullable=True))
    op.create_index(op.f('ix_endpoint_logs_organization'), 'endpoint_logs', ['organization'], unique=False)
    op.add_column('users', sa.Column('organization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'organization')
    op.drop_index(op.f('ix_endpoint_logs_organization'), table_name='endpoint_logs')
    op.drop_column('endpoint_logs', 'organization')
    # ### end Alembic commands ###
