"""message

Revision ID: b5bc33ce99aa
Revises: 8ecfceb8e277
Create Date: 2024-12-09 15:31:55.057399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bc33ce99aa'
down_revision = '8ecfceb8e277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
