name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Update the branch as needed
  # pull_request:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up Google Cloud authentication
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Authenticate Docker with GCP
      - name: Authenticate Docker
        run: |
          # Authenticate Docker to push to Artifact Registry
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      # Build and submit Docker image to Google Container Registry (GCR)
      - name: Build and submit Docker image
        run: |
          export TAG=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_PROJECT_REPO }}/${{ secrets.APP_NAME }}:${{ github.sha }}
          gcloud builds submit --tag $TAG
        continue-on-error: true
      
      # - name: Verify IAM roles for Service Account
      #   run: |
      #     # Ensure the deployer SA has the required roles:
      #     gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT_ID }} \
      #       --member="serviceAccount:${{ secrets.GCP_SERVICE_ACCOUNT_DEPLOYER_EMAIL }}" \
      #       --role="roles/run.admin"
      #     gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT_ID }} \
      #       --member="serviceAccount:${{ secrets.GCP_SERVICE_ACCOUNT_DEPLOYER_EMAIL }}" \
      #       --role="roles/iam.serviceAccountUser"

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          export APP=${{ secrets.APP_NAME }}
          export TAG=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_PROJECT_REPO }}/${{ secrets.APP_NAME }}
          export REGION=${{ secrets.GCP_REGION }}
          
          gcloud run deploy $APP --image $TAG --platform managed --region $REGION --allow-unauthenticated
