name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Update the branch as needed
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up Google Cloud authentication
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Authenticate Docker with GCP
      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker

      # Build and submit Docker image to Google Container Registry (GCR)
      - name: Build and submit Docker image
        run: |
          export TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.APP_NAME }}
          gcloud builds submit --tag $TAG
        continue-on-error: true

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          export APP=${{ secrets.APP_NAME }}
          export TAG=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${APP}
          export REGION=${{ secrets.GCP_REGION }}
          
          gcloud run deploy $APP --image $TAG --platform managed --region $REGION --allow-unauthenticated
